### ISSUE TITLE
[Feature Request] Destination Weather API

### ISSUE THREAD

**Issue by arsaboo** [abdullahselek/HerePy#2]
Can we please have the [destination weather API](https://developer.here.com/documentation/weather/topics/example-astronomy-forecast.html)? Here is one of the few providers that provide moon rise and moon set information, so it will be great if you can incorporate the same. Thanks!

**Comment by abdullahselek** [comment]
Hi @arsaboo thanks for your interest. I created a new api named `DestinationWeatherApi` specific to weather endpoint. Could you please have a look if that works for you?

**Comment by arsaboo** [comment]
Thanks @abdullahselek. Let me modify the package in HomeAssistant to use this one. I will close the comment for now. Thanks again for your effort.

**Comment by arsaboo** [comment]
@abdullahselek Looks like the docs need to be updated still.

**Comment by arsaboo** [comment]
```
>>> destinationAPI = herepy.DestinationWeatherApi('app_id', 'app_code')

Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    destinationAPI = herepy.DestinationWeatherApi('app_id', 'app_code')
AttributeError: 'module' object has no attribute 'DestinationWeatherApi'
```

**Comment by abdullahselek** [comment]
@arsaboo thanks for reminding me. I updated docs and released a new version `0.5.0` please try let me know.

**Comment by arsaboo** [comment]
@abdullahselek It is still not working for me. Here's the code that I'm using:
```
import herepy
destinationAPI = herepy.DestinationWeatherApi('app_id', 'app_code')
response = destinationAPI.forecast_astronomy("Chicago, IL")
print(response)
```
and here's the response:
```
["Request parameter 'product' does not conform with expected data type. Please check the documentation."]
```

Also, looks like the docs are still not complete. I did not see any information about DestinationWeatherApi in the readme.

**Comment by abdullahselek** [comment]
@arsaboo sorry for the late response, docs are available on http://herepy.readthedocs.org/en/latest/?badge=latest. And I will investigate the issue.

**Comment by abdullahselek** [comment]
Hey @arsaboo I updated `DestinationWeatherApi` and now it's available on version `0.6.2`. With new changes `forecast_astronomy`takes `destination` and `product` parameters. And there is a new enum type `WeatherProductType` for product parameter.

**Comment by abdullahselek** [comment]
Closing because of inactivity.
